version: '3.0'

services:
  db:
    image: mysql:5.7
    container_name: dockersploit-cve-2021-29447-DB
    volumes:
      - db_data:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: somewordpress
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.0-php8.0
    container_name: dockersploit-cve-2021-29447-WP
    ports:
      - 8000:80
      # EXPOSE 8000
      # HTTP
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data:
